import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { CopyToClipboard } from "react-copy-to-clipboard";
import toast, { Toaster } from 'react-hot-toast';
import { DB } from "../lib/db";


const Home: NextPage = () => {
  return (
    <>
      <Toaster />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <ul>
            {Object.keys(DB).map((key) => {
              return (
                <li key={key}> 
                  <div className={styles.title}>
                    <CopyToClipboard key={key} text={key} onCopy={() => {
                      toast("Copied URL to Clipboard, paste in Meta Tag Explorer")
                    }}>
                      <a href="#">{key}</a>
                    </CopyToClipboard>
                  </div>
                </li>
              );
            })}
          </ul>
        </main>
      </div>
    </>
  );
};

export default Home;
