import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { CopyToClipboard } from "react-copy-to-clipboard";
import toast, { Toaster } from "react-hot-toast";
import { DB } from "../lib/db";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { Context } from "vm";

const Home: NextPage<Context> = ({ username }) => {
  console.log({ username });
  return (
    <>
      <Toaster />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            property="og:image"
            content={`https://pup-gray.vercel.app/api/og?username=${
              username ?? ""
            }`}
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <ul>
            {Object.keys(DB).map((key) => {
              return (
                <li key={key}>
                  <div className={styles.title}>
                    <CopyToClipboard
                      key={`https://pup-gray.vercel.app?username=${key}`}
                      text={`https://pup-gray.vercel.app?username=${key}`}
                      onCopy={() => {
                        toast(
                          "Copied URL to Clipboard, paste in Meta Tag Explorer"
                        );
                      }}
                    >
                      <a href="#">{key}</a>
                    </CopyToClipboard>
                  </div>
                </li>
              );
            })}
          </ul>
        </main>
      </div>
    </>
  );
};

Home.getInitialProps = async (ctx: Context) => {
  let { username } = ctx.query;
  // ...
  return {
    username,
  };
};

export default Home;
